version: '3.8'

services:
  app:
    restart: unless-stopped
    build: ../
    working_dir: /app
    volumes:
      - ../public/:/app/public
      - ../src/:/app/src
      - ../logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - 8880:3000
  
  mongo:
    image: mongo:4.4.13
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_USER}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_PASS}"
    ports:
      - 27017:27017
    command: mongod --auth
    volumes:
      - ./mongo/data:/data
      - ./mongo/data/configdb:/data/configdb
      - ./mongo/data/db:/data/db

  redis:
    image: redis:7.0.2
    restart: unless-stopped
    ports:
      - 6479:6379
